import React, { useState } from "react";
import Layout from "../components/Layout";
// import { Card, Nav } from "react-bootstrap";
// import { Button } from "../components/common/forms/button";
// import Deposit from "../components/dashboard/deposit";
// import Withdrawal from "../components/dashboard/withdrawal";

const security = () => {
  return (
    <Layout title="financial">
      <div className="main-content">
        <div className="content-wrapper mt-4 row px-3">
          <div className="col-md-12">
            <div className="card Change_Password">
              <div className="card-header header-elements-inline">
                <h3 className="mb-0">Change Password</h3>
              </div>
              <div className="card-body">
                <form
                  action="https://crowd-growing.com/user/password"
                  method="post"
                >
                  <input
                    type="hidden"
                    name="_token"
                    value="lBgqLaH6PQVFfQRMhD8fSgVu8766raCJnHt8jRJF"
                  />{" "}
                  <div className="form-group row">
                    <label className="col-form-label col-lg-2">
                      Old password
                    </label>
                    <div className="col-lg-10">
                      <input
                        type="password"
                        name="current_password"
                        className="form-control"
                        // required=""
                      />
                    </div>
                  </div>
                  <div className="form-group row">
                    <label className="col-form-label col-lg-2">
                      New password
                    </label>
                    <div className="col-lg-10">
                      <input
                        type="password"
                        name="password"
                        className="form-control"
                        // required=""
                      />
                    </div>
                  </div>
                  <div className="form-group row">
                    <label className="col-form-label col-lg-2">
                      Confirm new password
                    </label>
                    <div className="col-lg-10">
                      <input
                        type="password"
                        name="password_confirmation"
                        className="form-control"
                        // required=""
                      />
                    </div>
                  </div>
                  <div className="text-right">
                    <button type="submit" className="btn btn-neutral">
                      Submit
                    </button>
                  </div>
                </form>
              </div>
            </div>

            <div className="row">
              <div className="col-lg-12">
                <div className="card Security bg-white">
                  <div className="card-header header-elements-inline">
                    <h3 className="mb-0">Two-Factor Security Option</h3>
                  </div>
                  <div className="card-body">
                    <div className="align-item-sm-center flex-sm-nowrap text-left">
                      <div className="">
                        <p>
                          Two-factor authentication is a method for protection
                          your web account. When it is activated you need to
                          enter not only your password, but also a special code.
                          You can receive this code by in mobile app. Even if
                          third person will find your password, then can't
                          access with that code.
                        </p>
                        <span className="badge badge-pill badge-primary">
                          Disabled
                        </span>
                        <p>
                          1) Install an authentication app on your device. Any
                          app that supports the Time-based One-Time Password
                          (TOTP) protocol should work.
                        </p>
                        <p>
                          2) Use the authenticator app to scan the barcode
                          below.
                        </p>
                        <img
                          src="https://chart.googleapis.com/chart?chs=200x200&amp;chld=M|0&amp;cht=qr&amp;chl=otpauth%3A%2F%2Ftotp%2Fcrowd-growing.com%3Asatoshi%40gmail.com%3Fsecret%3DAXNRWLLTI6LXQAZO%26issuer%3Dcrowd-growing.com"
                          style={{ maxWidth: "100%", height: "auto" }}
                        />
                        <p>
                          3) Enter the code generated by the authenticator app
                        </p>
                        <form
                          action="https://crowd-growing.com/user/2fa"
                          method="post"
                        >
                          <input
                            type="hidden"
                            name="_token"
                            value="2k803GMrtHeAWcf2r60aMZBLk5gWUP8b9quk3v5y"
                          />{" "}
                          <div className="form-group row">
                            <div className="col-lg-6">
                              <input
                                type="number"
                                name="code"
                                className="form-control"
                              />
                              <input
                                type="hidden"
                                name="vv"
                                value="AXNRWLLTI6LXQAZO"
                              />
                              <input type="hidden" name="type" value="1" />
                            </div>
                          </div>
                          <div className="text-left">
                            <button type="submit" className="btn btn-neutral">
                              Enable
                            </button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default security;
